// Code generated by bpf2go; DO NOT EDIT.

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lb4Backend struct {
	_      structs.HostLayout
	Ip     uint32
	Port   uint16
	Weight uint16
	Conns  uint32
}

type lb4ConnMeta struct {
	_           structs.HostLayout
	Ip          uint32
	Port        uint16
	_           [2]byte
	BackendIdx  uint32
	State       uint8
	_           [1]byte
	ServicePort uint16
}

type lb4IpPort struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint16
	_    [2]byte
}

// loadLb4 returns the embedded CollectionSpec for lb4.
func loadLb4() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Lb4Bytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lb4: %w", err)
	}

	return spec, err
}

// loadLb4Objects loads lb4 and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lb4Objects
//	*lb4Programs
//	*lb4Maps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLb4Objects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLb4()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lb4Specs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lb4Specs struct {
	lb4ProgramSpecs
	lb4MapSpecs
	lb4VariableSpecs
}

// lb4ProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lb4ProgramSpecs struct {
	XdpLoadBalancer *ebpf.ProgramSpec `ebpf:"xdp_load_balancer"`
}

// lb4MapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lb4MapSpecs struct {
	BackendCount  *ebpf.MapSpec `ebpf:"backend_count"`
	Backends      *ebpf.MapSpec `ebpf:"backends"`
	Conntrack     *ebpf.MapSpec `ebpf:"conntrack"`
	FreePorts     *ebpf.MapSpec `ebpf:"free_ports"`
	PortOwnership *ebpf.MapSpec `ebpf:"port_ownership"`
	Services      *ebpf.MapSpec `ebpf:"services"`
}

// lb4VariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lb4VariableSpecs struct {
}

// lb4Objects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLb4Objects or ebpf.CollectionSpec.LoadAndAssign.
type lb4Objects struct {
	lb4Programs
	lb4Maps
	lb4Variables
}

func (o *lb4Objects) Close() error {
	return _Lb4Close(
		&o.lb4Programs,
		&o.lb4Maps,
	)
}

// lb4Maps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLb4Objects or ebpf.CollectionSpec.LoadAndAssign.
type lb4Maps struct {
	BackendCount  *ebpf.Map `ebpf:"backend_count"`
	Backends      *ebpf.Map `ebpf:"backends"`
	Conntrack     *ebpf.Map `ebpf:"conntrack"`
	FreePorts     *ebpf.Map `ebpf:"free_ports"`
	PortOwnership *ebpf.Map `ebpf:"port_ownership"`
	Services      *ebpf.Map `ebpf:"services"`
}

func (m *lb4Maps) Close() error {
	return _Lb4Close(
		m.BackendCount,
		m.Backends,
		m.Conntrack,
		m.FreePorts,
		m.PortOwnership,
		m.Services,
	)
}

// lb4Variables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLb4Objects or ebpf.CollectionSpec.LoadAndAssign.
type lb4Variables struct {
}

// lb4Programs contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLb4Objects or ebpf.CollectionSpec.LoadAndAssign.
type lb4Programs struct {
	XdpLoadBalancer *ebpf.Program `ebpf:"xdp_load_balancer"`
}

func (p *lb4Programs) Close() error {
	return _Lb4Close(
		p.XdpLoadBalancer,
	)
}

func _Lb4Close(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lb4_bpf.o
var _Lb4Bytes []byte
